import { execFile } from "node:child_process";
import { constants as fsConstants } from "node:fs";
import { access, chmod, mkdir, readFile, realpath, writeFile } from "node:fs/promises";
import path from "node:path";
import { promisify } from "node:util";
import { fileURLToPath } from "node:url";
import prettier from "prettier";

type Mode = "check" | "discover-routemesh" | "write";
type MarkdownCell = number | string | null | undefined;

type RegistryChain = {
  accountActivityModel: string;
  aliases: string[];
  chainId: number;
  explorer: { addressUrl: string; txUrl: string };
  name: string;
  nativeCurrency: { symbol: string };
  slug: string;
};

type Registry = {
  chains?: RegistryChain[];
  schemaVersion?: number;
};

type BlockscoutOverlay = {
  hostedBy?: string;
  instanceUrl?: string;
  notes?: string;
  status: "absent" | "observed" | "unsafe";
};

type ChainOverlay = {
  blockscout: BlockscoutOverlay;
  chainscoutNamePattern?: string;
  etherscan: { notes?: string; support: "free" | "paid" | "unsupported" };
  fallbackPublicRpcs: string[];
  primaryPublicRpc: string;
  routeMesh: boolean;
};

type AtlasOverlay = {
  chains: Record<string, ChainOverlay>;
  metadata?: {
    blockscoutObservedAt?: string;
    etherscanProviderChainCount?: number;
    etherscanVerifiedAt?: string;
  };
};

const execFileAsync = promisify(execFile);
const scriptPath = fileURLToPath(import.meta.url);
const repoRoot = path.resolve(path.dirname(scriptPath), "..");
const skillRoot = path.join(repoRoot, "skills", "evm-atlas");
const referencesDir = path.join(skillRoot, "references");
const generatedDir = path.join(referencesDir, "generated");
const scriptsDir = path.join(skillRoot, "scripts");
const overlayPath = path.join(referencesDir, "atlas-overlays.json");
const generatedBy =
  "Generated by scripts/generate-evm-atlas.ts. Edit skills/evm-atlas/references/atlas-overlays.json instead.";
const etherscanChainsPath = path.join(generatedDir, "etherscan-chains.md");
const blockscoutChainsPath = path.join(generatedDir, "blockscout-chains.md");
const accountActivityModels = new Set(["cross-vm", "ethereum-eoa", "native-account-abstraction", "unknown"]);

const mode = parseMode(process.argv.slice(2));
const overlay = await readJson<AtlasOverlay>(overlayPath);
const registryDir = await resolveRegistryDir();
const registry = await readJson<Registry>(path.join(registryDir, "data", "chains.json"));
const registryChains = registry?.chains;

if (registry?.schemaVersion !== 2) {
  fail(`Unsupported crypto-registry chains schema version: ${registry?.schemaVersion ?? "missing"}.`);
}
if (!Array.isArray(registryChains) || registryChains.length === 0) {
  fail("crypto-registry data/chains.json did not contain a non-empty chains array.");
}

validateRegistryChains(registryChains);
validateOverlay(overlay, registryChains);
const chainsBySlug = new Map(registryChains.map((chain) => [chain.slug, chain]));
const chains = Object.keys(overlay.chains).map((slug) => {
  const chain = chainsBySlug.get(slug);
  if (!chain) fail(`Missing registry chain for overlay slug: ${slug}.`);
  return chain;
});

const files = new Map([
  [
    path.join(generatedDir, "target-mainnets.json"),
    await formatFile(
      path.join(generatedDir, "target-mainnets.json"),
      `${JSON.stringify({ chains: targetMainnets(chains, overlay) }, null, 2)}\n`,
    ),
  ],
  [
    path.join(generatedDir, "target-fallback-rpcs.json"),
    await formatFile(
      path.join(generatedDir, "target-fallback-rpcs.json"),
      `${JSON.stringify({ chains: targetFallbackRpcs(chains, overlay) }, null, 2)}\n`,
    ),
  ],
  [
    path.join(generatedDir, "chain-aliases.json"),
    await formatFile(
      path.join(generatedDir, "chain-aliases.json"),
      `${JSON.stringify({ aliases: chainAliases(chains) }, null, 2)}\n`,
    ),
  ],
  [etherscanChainsPath, await formatFile(etherscanChainsPath, etherscanChainsMarkdown(chains, overlay))],
  [blockscoutChainsPath, await formatFile(blockscoutChainsPath, blockscoutChainsMarkdown(chains, overlay))],
  [path.join(scriptsDir, "resolve-chain.sh"), resolveChainScript(chains, overlay)],
]);

if (mode === "write") {
  await mkdir(generatedDir, { recursive: true });
  for (const [filePath, content] of files) await writeFile(filePath, content);
  await chmod(path.join(scriptsDir, "resolve-chain.sh"), 0o755);
  process.stdout.write(`Generated ${files.size} evm-atlas files from ${registryDir}\n`);
} else if (mode === "discover-routemesh") {
  await discoverRouteMesh(chains, overlay);
} else {
  const dirty: string[] = [];
  for (const [filePath, expected] of files) {
    const actual = await readFile(filePath, "utf8").catch(() => "");
    if (actual !== expected) dirty.push(path.relative(repoRoot, filePath));
  }
  if (dirty.length > 0) {
    process.stderr.write("evm-atlas generated files are stale:\n");
    for (const file of dirty) process.stderr.write(`  - ${file}\n`);
    process.stderr.write("\nRun `just evm-atlas-generate`.\n");
    process.exit(1);
  }
  process.stdout.write(`evm-atlas generated files are current (${registryDir})\n`);
}

function parseMode(args: string[]): Mode {
  const arg = args[0];
  if (args.length !== 1 || !arg || !["--write", "--check", "--discover-routemesh"].includes(arg)) {
    fail("Usage: bun run scripts/generate-evm-atlas.ts --write|--check|--discover-routemesh");
  }
  if (arg === "--write") return "write";
  if (arg === "--check") return "check";
  return "discover-routemesh";
}

async function formatFile(filePath: string, content: string): Promise<string> {
  const options = await prettier.resolveConfig(filePath);
  return await prettier.format(content, { ...options, filepath: filePath });
}

async function readJson<T>(filePath: string): Promise<T> {
  try {
    return JSON.parse(await readFile(filePath, "utf8")) as T;
  } catch (error) {
    fail(`Failed to read JSON at ${filePath}: ${errorMessage(error)}`);
  }
}

async function resolveRegistryDir() {
  const candidates = [process.env.CRYPTO_REGISTRY_DIR, path.resolve(repoRoot, "..", "crypto-registry")].filter(
    (candidate): candidate is string => Boolean(candidate),
  );

  for (const candidate of candidates) {
    const resolved = path.resolve(candidate);
    const packageJsonPath = path.join(resolved, "package.json");
    try {
      await access(packageJsonPath, fsConstants.R_OK);
    } catch {
      continue;
    }
    const packageJson = await readJson<{ name?: string }>(packageJsonPath);
    if (packageJson.name !== "@prb/crypto-registry") {
      fail(`${resolved} is not @prb/crypto-registry (package name: ${packageJson.name ?? "missing"}).`);
    }
    return await realpath(resolved);
  }

  fail("Missing @prb/crypto-registry checkout. Set CRYPTO_REGISTRY_DIR or clone it at ../crypto-registry.");
}

function validateRegistryChains(registryChains: RegistryChain[]): void {
  for (const chain of registryChains) {
    if (!accountActivityModels.has(chain.accountActivityModel)) {
      fail(
        `${chain.slug}.accountActivityModel must be cross-vm, ethereum-eoa, native-account-abstraction, or unknown.`,
      );
    }
  }
}

function validateOverlay(data: AtlasOverlay, registryChains: Array<{ slug: string }>): void {
  if (!data || typeof data !== "object" || !data.chains || typeof data.chains !== "object") {
    fail("atlas-overlays.json must contain a chains object.");
  }

  const registrySlugs = new Set(registryChains.map((chain) => chain.slug));
  const overlaySlugs = new Set(Object.keys(data.chains));
  const missing = [...registrySlugs].filter((slug) => !overlaySlugs.has(slug));
  const unknown = [...overlaySlugs].filter((slug) => !registrySlugs.has(slug));
  if (missing.length > 0 || unknown.length > 0) {
    fail(
      [
        missing.length > 0 ? `Missing overlay rows: ${missing.join(", ")}` : "",
        unknown.length > 0 ? `Unknown overlay rows: ${unknown.join(", ")}` : "",
      ]
        .filter(Boolean)
        .join("\n"),
    );
  }

  for (const chain of registryChains) {
    const row = data.chains[chain.slug];
    if (!row) fail(`Missing overlay row: ${chain.slug}.`);
    assertString(row.primaryPublicRpc, `${chain.slug}.primaryPublicRpc`);
    assertStringArray(row.fallbackPublicRpcs, `${chain.slug}.fallbackPublicRpcs`);
    if (typeof row.routeMesh !== "boolean") fail(`${chain.slug}.routeMesh must be boolean.`);
    if (!["free", "paid", "unsupported"].includes(row.etherscan?.support)) {
      fail(`${chain.slug}.etherscan.support must be free, paid, or unsupported.`);
    }
    if (!["observed", "absent", "unsafe"].includes(row.blockscout?.status)) {
      fail(`${chain.slug}.blockscout.status must be observed, absent, or unsafe.`);
    }
    if (row.blockscout.status === "observed") {
      assertString(row.blockscout.hostedBy, `${chain.slug}.blockscout.hostedBy`);
      assertString(row.blockscout.instanceUrl, `${chain.slug}.blockscout.instanceUrl`);
    }
    if (row.blockscout.status === "unsafe") {
      assertString(row.blockscout.notes, `${chain.slug}.blockscout.notes`);
    }
    if (row.chainscoutNamePattern !== undefined) {
      assertString(row.chainscoutNamePattern, `${chain.slug}.chainscoutNamePattern`);
    }
  }
}

function assertString(value: unknown, name: string): asserts value is string {
  if (typeof value !== "string" || value.length === 0) fail(`${name} must be a non-empty string.`);
}

function assertStringArray(value: unknown, name: string): asserts value is string[] {
  if (
    !Array.isArray(value) ||
    value.length === 0 ||
    value.some((item) => typeof item !== "string" || item.length === 0)
  ) {
    fail(`${name} must be a non-empty string array.`);
  }
}

async function discoverRouteMesh(registryChains: RegistryChain[], data: AtlasOverlay): Promise<void> {
  let stdout: string;
  try {
    ({ stdout } = await execFileAsync("routemesh", ["chains", "--transport=rpc", "--output=json"]));
  } catch (error) {
    fail(`RouteMesh chains command failed: ${commandErrorMessage(error)}`);
  }

  let liveChains: Array<{ chain_id: string }>;
  try {
    liveChains = JSON.parse(stdout) as Array<{ chain_id: string }>;
  } catch (error) {
    fail(`RouteMesh chains command returned invalid JSON: ${errorMessage(error)}`);
  }
  if (
    !Array.isArray(liveChains) ||
    liveChains.some((chain) => typeof chain?.chain_id !== "string" || !/^[1-9][0-9]*$/.test(chain.chain_id))
  ) {
    fail("RouteMesh chains command returned an invalid chain catalog.");
  }
  const liveChainIds = new Set(liveChains.map((chain) => Number(chain.chain_id)));

  // Patch the raw text in place instead of round-tripping through JSON.stringify, so the
  // hand-formatted overlay (compact single-line arrays/objects) isn't reflowed wholesale.
  let text = await readFile(overlayPath, "utf8");
  const changes: string[] = [];
  for (const chain of registryChains) {
    const live = liveChainIds.has(chain.chainId);
    const row = overlayRow(data, chain);
    if (row.routeMesh === live) continue;
    const pattern = new RegExp(`("${escapeRegExp(chain.slug)}":\\s*\\{[\\s\\S]*?"routeMesh":\\s*)(?:true|false)`);
    if (!pattern.test(text)) fail(`Could not locate ${chain.slug}.routeMesh in atlas-overlays.json.`);
    text = text.replace(pattern, `$1${live}`);
    changes.push(`${chain.name} (${chain.slug}): ${row.routeMesh} -> ${live}`);
  }

  const today = new Date().toISOString().slice(0, 10);
  if (/"routeMeshVerifiedAt":\s*"[^"]*"/.test(text)) {
    text = text.replace(/"routeMeshVerifiedAt":\s*"[^"]*"/, `"routeMeshVerifiedAt": "${today}"`);
  } else {
    const indent = text.match(/\n(\s*)"etherscanVerifiedAt":/)?.[1] ?? "    ";
    text = text.replace(/("etherscanVerifiedAt":\s*"[^"]*")/, `$1,\n${indent}"routeMeshVerifiedAt": "${today}"`);
  }
  await writeFile(overlayPath, text);

  if (changes.length > 0) {
    process.stdout.write(`Updated routeMesh for ${changes.length} chain(s):\n`);
    for (const change of changes) process.stdout.write(`  - ${change}\n`);
    process.stdout.write("\nRun `just evm-atlas-generate` to propagate into target-mainnets.json.\n");
  } else {
    process.stdout.write(`All ${registryChains.length} target chains already match RouteMesh's live support list.\n`);
  }
}

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

function targetMainnets(registryChains: RegistryChain[], data: AtlasOverlay) {
  return registryChains.map((chain) => {
    const row = overlayRow(data, chain);
    return {
      chainName: chain.name,
      chainId: chain.chainId,
      slug: chain.slug,
      accountActivityModel: chain.accountActivityModel,
      primaryPublicRpc: row.primaryPublicRpc,
      nativeCurrencySymbol: chain.nativeCurrency.symbol,
      explorerUrl: explorerBaseUrl(chain),
      routeMesh: row.routeMesh,
    };
  });
}

function targetFallbackRpcs(registryChains: RegistryChain[], data: AtlasOverlay) {
  return registryChains.map((chain) => ({
    chainName: chain.name,
    chainId: chain.chainId,
    fallbackPublicRpcs: overlayRow(data, chain).fallbackPublicRpcs,
  }));
}

function chainAliases(registryChains: RegistryChain[]) {
  const rows: Array<{ alias: string; chainId: number; chainName: string }> = [];
  const seen = new Map<string, RegistryChain>();
  for (const chain of registryChains) {
    const slugAlias = slugDiffersFromName(chain) ? [chain.slug] : [];
    for (const alias of [...slugAlias, ...chain.aliases]) {
      const key = alias.toLowerCase();
      const existing = seen.get(key);
      if (existing?.chainId === chain.chainId) continue;
      if (existing) fail(`Alias ${alias} is ambiguous: ${existing.name} and ${chain.name}.`);
      seen.set(key, chain);
      rows.push({ alias, chainName: chain.name, chainId: chain.chainId });
    }
  }
  return rows;
}

function slugDiffersFromName(chain: RegistryChain): boolean {
  return chain.slug !== chain.name.toLowerCase().replaceAll(" ", "-");
}

function explorerBaseUrl(chain: RegistryChain): string {
  const addressBase = stripSuffix(chain.explorer.addressUrl, "/address/{address}", `${chain.slug}.explorer.addressUrl`);
  const txBase = stripSuffix(chain.explorer.txUrl, "/tx/{tx_hash}", `${chain.slug}.explorer.txUrl`);
  if (addressBase !== txBase) fail(`${chain.slug} explorer address/tx base URLs differ.`);
  return addressBase;
}

function stripSuffix(value: string, suffix: string, name: string): string {
  if (!value.endsWith(suffix)) fail(`${name} must end with ${suffix}.`);
  return value.slice(0, -suffix.length);
}

function etherscanChainsMarkdown(registryChains: RegistryChain[], data: AtlasOverlay): string {
  const rowsBySupport = groupBy(registryChains, (chain) => overlayRow(data, chain).etherscan.support);
  const meta = data.metadata ?? {};
  return [
    "# Etherscan Supported Target Chains Reference",
    "",
    `<!-- ${generatedBy} -->`,
    "",
    "Source: <https://docs.etherscan.io/supported-chains>",
    "Live list: <https://api.etherscan.io/v2/chainlist> (returns the provider's authoritative `chainid` set)",
    "",
    `Verified against the live \`chainlist\` endpoint on ${meta.etherscanVerifiedAt} (${meta.etherscanProviderChainCount} provider chains). This file intentionally lists only chains from \`references/generated/target-mainnets.json\`; provider-supported chains outside that list are out of scope for this skill.`,
    "",
    "## Target Mainnets (Free Tier Available)",
    "",
    markdownTable(
      ["Chain", "Chain ID", "Notes"],
      (rowsBySupport.free ?? []).map((chain) => [
        chain.name,
        code(chain.chainId),
        overlayRow(data, chain).etherscan.notes ?? "",
      ]),
    ),
    "",
    "## Target Mainnets (Paid Plan Required)",
    "",
    "The following target chains require a paid Etherscan plan for data endpoints (balances, transactions, logs, etc.). **Lite ($49/mo) is sufficient**; `module=contract` endpoints (`getsourcecode`, `getabi`, etc.) work on every plan.",
    "",
    markdownTable(
      ["Chain", "Chain ID"],
      (rowsBySupport.paid ?? []).map((chain) => [chain.name, code(chain.chainId)]),
    ),
    "",
    "## Target Mainnets Not on Etherscan V2",
    "",
    "Route these target chains to Blockscout when available, then to the `primaryPublicRpc` from `references/generated/target-mainnets.json` if needed. Do not query Etherscan V2 for them.",
    "",
    markdownTable(
      ["Chain", "Chain ID", "Notes"],
      (rowsBySupport.unsupported ?? []).map((chain) => [
        chain.name,
        code(chain.chainId),
        overlayRow(data, chain).etherscan.notes ?? "Not returned by the live chainlist",
      ]),
    ),
    "",
    "Testnets are outside this skill's target list. If the user asks about any non-target chain, ask them to file a feature request in <https://github.com/PaulRBerg/agent-skills>.",
    "",
  ].join("\n");
}

function blockscoutChainsMarkdown(registryChains: RegistryChain[], data: AtlasOverlay): string {
  const observed = registryChains.filter((chain) => overlayRow(data, chain).blockscout.status === "observed");
  const absentOrUnsafe = registryChains.filter((chain) => overlayRow(data, chain).blockscout.status !== "observed");
  return [
    "# Target Chains & Chainscout",
    "",
    `<!-- ${generatedBy} -->`,
    "",
    "Blockscout and Chainscout index many EVM networks, but this skill only uses them for chains in `references/generated/target-mainnets.json`. Do not use Chainscout to expand scope. If a requested chain is not in that JSON file, ask the user to file a feature request in <https://github.com/PaulRBerg/agent-skills>.",
    "",
    "## Chainscout API",
    "",
    "No API key required. Live UI: <https://chains.blockscout.com/>",
    "",
    markdownTable(
      ["Endpoint", "Returns"],
      [
        [code("GET https://chains.blockscout.com/api/chains"), "Object keyed by `chain_id` -> metadata (all networks)"],
        [code("GET https://chains.blockscout.com/api/chains/{id}"), "Metadata for one chain"],
      ],
    ),
    "",
    "Single-chain response shape:",
    "",
    "```json",
    "{",
    '  "name": "Gnosis",',
    '  "native_currency": "XDAI",',
    '  "isTestnet": false,',
    '  "layer": 1,',
    '  "rollupType": null,',
    '  "ecosystem": "Ethereum",',
    '  "explorers": [{ "url": "https://gnosis.blockscout.com/", "hostedBy": "blockscout" }]',
    "}",
    "```",
    "",
    "`explorers[].hostedBy`:",
    "",
    "- `blockscout` - Blockscout-operated; candidate for the unified PRO host (`api.blockscout.com/{chain_id}/...`). Still confirm with a live call; not every hosted target chain is fronted by the PRO host.",
    "- anything else - community-operated. Per-instance only; use `explorers[].url` directly (no key).",
    "",
    "Use `scripts/resolve-chain.sh <chain_id>` to extract these fields as `key=value` lines. The helper refuses non-target chain IDs and rejects Chainscout responses whose name does not match the target chain. For **name -> `chain_id`**, use `references/generated/target-mainnets.json` and `references/generated/chain-aliases.json` first.",
    "",
    "## Target Chains Observed in Chainscout",
    "",
    `Observed on ${data.metadata?.blockscoutObservedAt}. Presence here does not override the canonical explorer/RPC metadata in \`references/generated/target-mainnets.json\`.`,
    "",
    markdownTable(
      ["Chain", "`chain_id`", "Native", "Hosted by", "Instance URL", "Notes"],
      observed.map((chain) => {
        const blockscout = overlayRow(data, chain).blockscout;
        return [
          chain.name,
          code(chain.chainId),
          chain.nativeCurrency.symbol,
          blockscout.hostedBy,
          blockscout.instanceUrl,
          blockscout.notes ?? "",
        ];
      }),
    ),
    "",
    "## Target Chains Absent or Unsafe in Chainscout",
    "",
    "Use Etherscan, a documented exceptional-history route, or the public RPC/explorer in `references/generated/target-mainnets.json` for these.",
    "",
    markdownTable(
      ["Chain", "`chain_id`", "Notes"],
      absentOrUnsafe.map((chain) => [chain.name, code(chain.chainId), overlayRow(data, chain).blockscout.notes]),
    ),
    "",
    "## Contributing",
    "",
    "Missing or wrong Blockscout registry data is fixed via PR to <https://github.com/blockscout/chainscout>. Requests to add non-target chains to this skill belong in <https://github.com/PaulRBerg/agent-skills>.",
    "",
  ].join("\n");
}

function resolveChainScript(registryChains: RegistryChain[], data: AtlasOverlay): string {
  const cases = registryChains.map((chain) => {
    const pattern = overlayRow(data, chain).chainscoutNamePattern ?? chain.name;
    return `    ${chain.chainId}) printf '%s\\n' '${singleQuote(pattern)}' ;;`;
  });
  const unsafeCases = registryChains
    .filter((chain) => overlayRow(data, chain).blockscout.status === "unsafe")
    .map((chain) => {
      const notes = overlayRow(data, chain).blockscout.notes ?? "";
      return `    ${chain.chainId}) printf '%s\\n' '${singleQuote(notes)}' ;;`;
    });
  const unsafeShellcheckDirectives = registryChains.some(
    (chain) =>
      overlayRow(data, chain).blockscout.status === "unsafe" &&
      (overlayRow(data, chain).blockscout.notes?.includes("`") ?? false),
  )
    ? ["  # shellcheck disable=SC2016"]
    : [];

  return [
    "#!/bin/bash",
    "# resolve-chain.sh - Resolve a target chain_id to its Blockscout instance via Chainscout.",
    "#",
    `# ${generatedBy}`,
    "#",
    "# Usage: resolve-chain.sh <target_chain_id>",
    "#",
    "# Outputs key=value lines on stdout:",
    "#   chain_id=<int>",
    "#   name=<string>",
    "#   native_currency=<symbol>",
    "#   instance_url=<url, ends in />",
    "#   hosted_by=<blockscout|other>",
    "#   is_testnet=<true|false>",
    "#   layer=<int|>",
    "#   rollup_type=<string|>",
    "#",
    "# No API key required. Source: https://chains.blockscout.com/",
    "# Scope is intentionally limited to skills/evm-atlas/references/generated/target-mainnets.json.",
    "",
    "set -eu",
    "",
    'if [ $# -lt 1 ] || [ -z "${1:-}" ]; then',
    '  echo "Usage: resolve-chain.sh <chain_id>" >&2',
    "  exit 1",
    "fi",
    "",
    'chain_id="$1"',
    "",
    "target_name_pattern() {",
    '  case "$1" in',
    ...cases,
    "    *)",
    "      return 1",
    "      ;;",
    "  esac",
    "}",
    "",
    'expected_pattern=$(target_name_pattern "$chain_id") || {',
    '  echo "Error: chain_id=$chain_id is outside the evm-atlas target list." >&2',
    '  echo "Ask the user to file a feature request in https://github.com/PaulRBerg/agent-skills" >&2',
    "  exit 2",
    "}",
    "",
    "unsafe_reason() {",
    ...unsafeShellcheckDirectives,
    '  case "$1" in',
    ...unsafeCases,
    "    *)",
    "      return 1",
    "      ;;",
    "  esac",
    "}",
    "",
    'if reason=$(unsafe_reason "$chain_id"); then',
    '  echo "Error: chain_id=$chain_id is marked unsafe in the evm-atlas overlay." >&2',
    '  echo "Reason: $reason" >&2',
    "  exit 1",
    "fi",
    "",
    'resp=$(curl -fsS "https://chains.blockscout.com/api/chains/$chain_id" 2>/dev/null) || {',
    '  echo "Error: Chainscout request failed for chain_id=$chain_id" >&2',
    "  exit 1",
    "}",
    "",
    'sval() { printf \'%s\' "$resp" | grep -o "\\"$1\\":\\"[^\\"]*\\"" | head -1 | sed \'s/.*:"\\(.*\\)"/\\1/\'; }',
    'nval() { printf \'%s\' "$resp" | grep -o "\\"$1\\":[0-9]*" | head -1 | grep -o \'[0-9]*\'; }',
    'bval() { printf \'%s\' "$resp" | grep -oE "\\"$1\\":(true|false)" | head -1 | sed \'s/.*://\'; }',
    "",
    'name=$(sval "name")',
    'if [ -z "$name" ]; then',
    '  echo "Error: chain_id=$chain_id not found in Chainscout" >&2',
    "  exit 1",
    "fi",
    'if ! printf \'%s\' "$name" | grep -Eiq "$expected_pattern"; then',
    '  echo "Error: Chainscout returned name=$name for target chain_id=$chain_id; expected match=$expected_pattern" >&2',
    '  echo "Refusing to use a non-target Chainscout registry match." >&2',
    "  exit 1",
    "fi",
    "",
    'native=$(sval "native_currency")',
    '# "url" only appears inside explorers[]; the first is the primary explorer.',
    'instance=$(printf \'%s\' "$resp" | grep -o \'"url":"[^"]*"\' | head -1 | sed \'s/.*:"\\(.*\\)"/\\1/\')',
    'hosted=$(sval "hostedBy")',
    'testnet=$(bval "isTestnet")',
    'layer=$(nval "layer")',
    'rollup=$(sval "rollupType")',
    "",
    "cat <<EOF",
    "chain_id=$chain_id",
    "name=$name",
    "native_currency=$native",
    "instance_url=$instance",
    "hosted_by=$hosted",
    "is_testnet=$testnet",
    "layer=$layer",
    "rollup_type=$rollup",
    "EOF",
    "",
  ].join("\n");
}

function groupBy<T>(items: T[], keyFn: (item: T) => string): Record<string, T[]> {
  const result: Record<string, T[]> = {};
  for (const item of items) {
    const key = keyFn(item);
    result[key] ??= [];
    result[key].push(item);
  }
  return result;
}

function overlayRow(data: AtlasOverlay, chain: Pick<RegistryChain, "slug">): ChainOverlay {
  const row = data.chains[chain.slug];
  if (!row) fail(`Missing overlay row: ${chain.slug}.`);
  return row;
}

function markdownTable(headers: string[], rows: MarkdownCell[][]): string {
  const widths = headers.map((header, index) =>
    Math.max(header.length, ...rows.map((row) => String(row[index] ?? "").length)),
  );
  const formatRow = (row: MarkdownCell[]) =>
    `| ${row.map((cell, index) => String(cell ?? "").padEnd(widths[index] ?? 0)).join(" | ")} |`;
  return [formatRow(headers), formatRow(widths.map((width) => "-".repeat(width))), ...rows.map(formatRow)].join("\n");
}

function code(value: number | string): string {
  return `\`${value}\``;
}

function singleQuote(value: string): string {
  return value.replaceAll("'", "'\\''");
}

function errorMessage(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}

function commandErrorMessage(error: unknown): string {
  if (
    error !== null &&
    typeof error === "object" &&
    "stderr" in error &&
    typeof error.stderr === "string" &&
    error.stderr.trim()
  ) {
    return error.stderr.trim();
  }
  return errorMessage(error);
}

function fail(message: string): never {
  process.stderr.write(`${message}\n`);
  process.exit(1);
}
